# Generated by Django 5.0.7 on 2024-07-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourite_items',
            field=models.ManyToManyField(related_name='favourite_items_users', to='api.item'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='items',
            field=models.ManyToManyField(related_name='items_users', to='api.item'),
        ),
    ]
